title: Zeyad Mahmoud
description: Junior Penetration Tester
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# The sidebar logo
logo: https://github.com/zeyad-mahmoud7.png

favicon: /favicon.ico
