title: Zeyad Mahmoud
description: A curious guy
baseurl: "" 
url: "https://zeyad-mahmoud7.github.io"

# Social Links
linkedin_username: zeyad-mahmoud7
github_username: zeyad-mahmoud7

# Theme Settings
remote_theme: jekyll/minima # Or your preferred dark theme
